# Generated by Django 2.0.2 on 2019-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='Digite a descrição da Disciplina', max_length=512, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(default=None, help_text='Digite o nome da Disciplina', max_length=128, verbose_name='Título'),
        ),
    ]
