# Generated by Django 2.0.2 on 2019-11-13 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191113_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Professor'),
        ),
    ]
