# Generated by Django 2.0.2 on 2019-11-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191113_0800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='uuid',
        ),
    ]
