# Generated by Django 2.0.2 on 2019-06-11 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190611_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Unico'),
        ),
    ]
