# Generated by Django 2.0.2 on 2019-11-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191121_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_profile',
            field=models.CharField(choices=[('1', 'Professor'), ('2', 'Aluno')], default=1, max_length=1, verbose_name='Tipo do perfil'),
        ),
    ]
