# Generated by Django 2.0.2 on 2019-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191122_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=None, max_length=50, verbose_name='Nome Completo'),
        ),
    ]
