# Generated by Django 2.0.2 on 2019-06-25 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, help_text='Digite o nome da disciplina', max_length=128, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, default=None, help_text='Digite a descrição da disciplina', max_length=512, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data criação')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data alteração')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
