# Generated by Django 2.0.2 on 2019-07-09 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, help_text='Digite o nome da disciplina', max_length=128, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, default=None, help_text='Digite a descrição da disciplina', max_length=512, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, help_text='Digite o nome da disciplina', max_length=128, verbose_name='Título')),
                ('descricao', models.CharField(blank=True, default=None, help_text='Digite a descrição da disciplina', max_length=512, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Disciplina', verbose_name='Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_criacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário cadastro')),
            ],
        ),
    ]
