# Generated by Django 2.0.2 on 2019-09-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('date_edit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('alternative_A', models.CharField(default=None, max_length=512, verbose_name='Alternativa A')),
                ('alternative_B', models.CharField(default=None, max_length=512, verbose_name='Alternativa B')),
                ('alternative_C', models.CharField(default=None, max_length=512, verbose_name='Alternativa C')),
                ('alternative_D', models.CharField(default=None, max_length=512, verbose_name='Alternativa D')),
                ('alternative_true', models.CharField(max_length=16, verbose_name='Alternativa correta')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Digite o nome da Discipline', max_length=512, verbose_name='Título')),
                ('description', models.CharField(blank=True, default=None, help_text='Digite a descrição da Discipline', max_length=1024, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('date_edit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('last_id', models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Proximo')),
                ('time_solution', models.CharField(default=None, help_text='Tempo para resolver a questão', max_length=16, verbose_name='Tempo de solução')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Digite o nome da Discipline', max_length=128, verbose_name='Título')),
                ('description', models.CharField(blank=True, default=None, help_text='Digite a descrição da Discipline', max_length=512, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('date_edit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Discipline', verbose_name='Discipline')),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('description', models.CharField(blank=True, default=None, help_text='Digite a descrição da Discipline', max_length=1024, null=True, verbose_name='Descrição')),
                ('points', models.CharField(blank=True, default='0', help_text='Pontos ganhos', max_length=5, null=True, verbose_name='Pontos')),
                ('discipline', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Discipline')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reward_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('reward', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.reward')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quizzes', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='question_related', to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_create',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
