# Generated by Django 2.0.2 on 2019-07-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='data_criacao',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='data_alteracao',
            new_name='date_edit',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='quizzes',
            old_name='User_criacao',
            new_name='user_create',
        ),
    ]
