# Generated by Django 2.0.2 on 2019-07-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190722_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizzes',
            old_name='Discipline',
            new_name='discipline',
        ),
    ]
