# Generated by Django 2.0.2 on 2019-07-13 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quizzes_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='usuario_criacao',
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Disciplina', verbose_name='Disciplina'),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
