# Generated by Django 2.0.2 on 2019-07-31 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_auto_20190722_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_create',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, default=None, help_text='Digite a descrição da Discipline', max_length=1024, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default=None, help_text='Digite o nome da Discipline', max_length=512, verbose_name='Título'),
        ),
    ]
