# Generated by Django 2.0.2 on 2019-07-20 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_auto_20190713_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Digite o nome da disciplina', max_length=128, verbose_name='Título')),
                ('description', models.CharField(blank=True, default=None, help_text='Digite a descrição da disciplina', max_length=512, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('date_edit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('alternative_A', models.CharField(default=None, max_length=512, verbose_name='Alternativa A')),
                ('alternative_B', models.CharField(default=None, max_length=512, verbose_name='Alternativa B')),
                ('alternative_C', models.CharField(default=None, max_length=512, verbose_name='Alternativa C')),
                ('alternative_D', models.CharField(default=None, max_length=512, verbose_name='Alternativa D')),
                ('alternative_true', models.CharField(max_length=16, verbose_name='Alternativa correta')),
                ('time_solution', models.CharField(default=None, help_text='Tempo para resolver a questão', max_length=16, verbose_name='Tempo de solução')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.Quizzes', verbose_name='Quiz')),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
