# Generated by Django 2.0.2 on 2019-08-27 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disciplines_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20190803_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('description', models.CharField(blank=True, default=None, help_text='Digite a descrição da Discipline', max_length=1024, null=True, verbose_name='Descrição')),
                ('points', models.CharField(blank=True, default='0', help_text='Pontos ganhos', max_length=5, null=True, verbose_name='Pontos')),
                ('discipline', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Discipline')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reward_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('reward', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.reward')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
