# Generated by Django 2.0.2 on 2019-08-06 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20190722_2313'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Digite o nome do game', max_length=512, verbose_name='Título')),
                ('description', models.CharField(blank=True, default=None, help_text='Digite a descrição do game', max_length=1024, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_edit', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data alteração')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('B', 'Bloqueado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Discipline', verbose_name='Quiz')),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
