# Generated by Django 2.0.2 on 2019-09-02 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('O', 'Online'), ('E', 'Executado'), ('D', 'Desativado')], default='A', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, help_text='Digite o nome do game', max_length=512, verbose_name='Título')),
                ('description', models.CharField(blank=True, default=None, help_text='Digite a descrição do game', max_length=1024, null=True, verbose_name='Descrição')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('O', 'Online'), ('E', 'Executado'), ('D', 'Desativado')], default='A', max_length=15)),
                ('students', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Participantes')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Discipline', verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('F', 'Finalizado')], default='A', max_length=15, verbose_name='Status')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único')),
                ('quiz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Quizzes')),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='played',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Played', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='game',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='game',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Game'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='user_create',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
