# Generated by Django 2.0.2 on 2019-08-20 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0005_auto_20190803_1920'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Played',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('E', 'Executando'), ('F', 'Finalizado')], default='A', max_length=15, verbose_name='Status')),
                ('quiz', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.Quizzes')),
                ('user_create', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='date_edit',
        ),
        migrations.AddField(
            model_name='game',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data criação'),
        ),
        migrations.AddField(
            model_name='game',
            name='students',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='game',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Discipline', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('O', 'Online'), ('E', 'Executado'), ('D', 'Desativado')], default='A', max_length=15),
        ),
        migrations.AddField(
            model_name='game',
            name='played',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Played', verbose_name='Quiz'),
        ),
    ]
