# Generated by Django 2.0.2 on 2019-08-20 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190820_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Played', verbose_name='Quiz'),
        ),
    ]
