# Generated by Django 2.0.2 on 2019-08-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190806_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='students',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Participantes'),
        ),
    ]
