# Generated by Django 2.0.2 on 2019-08-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190820_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='played',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('F', 'Finalizado')], default='A', max_length=15, verbose_name='Status'),
        ),
    ]
