# Generated by Django 2.0.2 on 2019-08-20 23:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190820_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='played',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identificador Único'),
        ),
    ]
